= DRAFT Procedure for setting attenuation for RDBEs
E. Himwich, C. Ruszczyk, K. Imai, C. Coughlin, M. Poirier, A. Burns
Version 0.8 - August 2020

== Introduction

The procedure below can be used to adjust the attenuation settings
depending on the observing mode. The observing mode usually stays the
same for a given experiment type. More than one experiment type may
use the same mode.

Before a new observing mode is used at a station for the first time,
the procedure can be used to adjust the attenuation and inform the
Coordinating Center of the correct settings to use in future
schedules. The determined values can be used locally until the
schedules are using them as the default.

If the procedure has not been attempted yet for some observing modes that a station
is already using, it should be performed for those modes and the
Coordinating Center informed if any changes are needed.

== Dealing with changes

Due to changes in the situation at the station, e.g., having a warm
receiver or a loss of signal chain gain, it may become necessary to
adjust the values.  If not otherwise apparent, this may become evident
because the RDBE RMSs are not reaching the target value of about 20.

At that point, the procedure can be re-run or an appropriate _ad hoc_
change to the values can be used to correct the situation.  As an
example of the latter approach, an increase in the overall signal
level of 10 dB might be compensated for by increasing the RFD and/or
UDC attentions by a net total of 10 dB. Of course, if there this is
caused by a failure of some component, the failure should be addressed
as soon as practical.

Once the level is corrected, it should be considered whether the issue
is likely to continue long enough for it to be worth sending new
values to the Coordinating Center or to just adjust the schedule
values locally until the issue is resolved. If the normal setting is
made with the procedure below, resulting in RDBE attenuator values of
10-15 dB, the system should be able tolerate level changes of in a
range of up to about ±10 dB fairly well in the short-term (but that
should not be a long term solution).

== How attenations interact

The total attenuation for each IF signal is the sum of the RFD, UDC,
and RDBE attenuation in the signal path for that IF channel. For a
given RFD and UDC attenuation setting, the RDBE will try to adjust its
attenuation to reach the nominal RMS, usually 20, in each channel.

Suppose that has happened, i.e., the RMS has adjusted to 20. Then the
total of the attenuation for that channel has reached the right level
to get 20 as the RMS level. Let's say that the attenuations are RFD:
5, UDC: 10, and RDBE: 15. This gives a total attenuation of 30 dB.

Now suppose the UDC attenuation for that IF is increased by 5 dB. To
get an RMS of 20, the RDBE will have to reduce its attenuation by
about the same amount.  Now the attenuations should be about RFD: 5,
UDC: 15, and RDBE: 10. The total is still 30 dB, but it is distributed
differently.

This is an example of the fact that the RDBE attenuation changes in
the opposite direct of the RFD plus UDC attention. What is being held
constant is the RMS of 20 (assuming it is possible to get to 20).

== Procedure

The procedure in this section provides a lot of detail to assist users
that are attempting this for the first time. More experienced users
may not need so much detail, but may still find it useful for
reference.

. Point the antenna to zenith on a clear day (hopefully there is not a lot of RFI).

. In the FS, open a procedure library for an experiment of the type that you want to make adjustments for, e.g. for a `vo` at `K2`:

+
    proc=vo0202k2

. Using _pfmed_, make a copy of `ifdbb`, maybe `_ifdt_`. In _pfmed_:

+
    st,ifdbb,ifdt

+

WARNING:  You must use _pfmed_ to modify procedures to keep them in sync
with the FS. Help is available in _pfmed_ with the `help` command.
Commands support tab-completion where it is useful.

. Use _pfmed_ to make changes to `_ifdt_` for these steps:

+

IMPORTANT:  You must exit _pfmed_ each time you make a change before
re-executing the procedure to test the effect. Use the `ex` commands
to exit _pfmed_.

+

[TIP]
====

You can use the _pfmed_ `vi` command to edit the procedure with `vi`,
e.g., `vi,ifdt`. This will also work for _emacs_ with `emacs,ifdt`. If
you would like to use a different editor you can specify it by setting
the `EDITOR` environment variable. For example to use _nano_, you can
use:

`export EDITOR=nano`

before you enter _pfmed_ (this is only needed once per window, or text
terminal login, instance; it could be added to `~oper/.profile` for
use in future logins). Then use the `ed,ifdt` command inside _pfmed_
to edit the procedure.

====

+

.. Set all RFD attenuators to `*3*`

+

NOTE: If you don't have an RFD, set any attenuation before the RDBEs
appropriately. If there are just UDCs, a good starting value might be
`*20*`. Use the value you chose in place of the `*10*` in the next step.

.. Set all UDC attenuators to `*10*`

.. Iterate the following steps to get nominal RMSs of `20`:

...  Check the RMS values for the current setup:

+
    ifdt
    rdbe_atten=
+

TIP: `help=rdbe_atten` will display a help page for `rdbe_atten`
command that explains what it does and its output.

... If too high, increase individual UDC attenuators to get the RMSs closer to  `20`

... If a UDC attenuator maxes out, increase the corresponding RFD attenuator (by 3-6) and try again

+

[NOTE]
====

Adjusting the RFD attenuation may affect other channels, you may need
to trim their UDC settings again. The typical correspondence of RFD
channels to UDCs/IFs is given in <<rfdchannels,Table 1>>.

.RFD Channels
[[rfdchannels]]
|===============
| RFD Channel | Signal |UDC Channel|RDBE IF

|  0|       H-pol Low|A-0| A-0
|  1|       V-pol Low|A-1| A-1
|  2|       H-pol High|BCD-0| BCD-0
|  3|       V-pol High|BCD-1|BCD-1
|===============
====

+

.. Once all RMS are nominal (~`20`), look at the RDBE attenuator values

... Adjust the UDC attenuators to put the RDBE attenuators in the range `10`-`15` if possible

... If you reach the end of the UDC attenuator range, adjust the corresponding RFD attenuator by 3 and try again

. When finished,  rename your old copy of `ifdbb` to `ifdbb_old` and rename `ifdt` to `ifdbb`. In _pfmed_:

+

  rn,ifdbb,ifdd_old
  rn,ifdt,ifdbb

+

and send the new version  to the IVS Coordinator Center (`ivscc@lists.nasa.gov`) for use
in future schedules.  Please include the experiment type(s) it is to
be used for in your message.

== Appendix A - Example ifdbb procedure

The following is a listing of the `ifdbb` procedure that was developed
for KPGO 12m for `vo` and `v2` experiments, using this procedure.
This will not be the right procedure in every detail for other stations
or observing modes. It is just offered as an example.

....
lo=
lo=loa0,2472.4,usb,lcp,5
lo=loa1,2472.4,usb,rcp,5
lo=lob0,4712.4,usb,lcp,5
lo=lob1,4712.4,usb,rcp,5
lo=loc0,5832.4,usb,lcp,5
lo=loc1,5832.4,usb,rcp,5
lo=lod0,9672.4,usb,lcp,5
lo=lod1,9672.4,usb,rcp,5
"
sy=popen 's_client -h udca -c udc_lo=2472.4 2>&1' -n udcca
sy=popen 's_client -h udcb -c udc_lo=4712.4 2>&1' -n udccb
sy=popen 's_client -h udcc -c udc_lo=5832.4 2>&1' -n udccc
sy=popen 's_client -h udcd -c udc_lo=9672.4 2>&1' -n udccd
"
sy=popen 's_client -h udca -c udc_atten=0:17 2>&1' -n udcca
sy=popen 's_client -h udcb -c udc_atten=0:25 2>&1' -n udccb
sy=popen 's_client -h udcc -c udc_atten=0:30 2>&1' -n udccc
sy=popen 's_client -h udcd -c udc_atten=0:5 2>&1' -n udccd
sy=popen 's_client -h udca -c udc_atten=1:17 2>&1' -n udcca
sy=popen 's_client -h udcb -c udc_atten=1:27 2>&1' -n udccb
sy=popen 's_client -h udcc -c udc_atten=1:27 2>&1' -n udccc
sy=popen 's_client -h udcd -c udc_atten=1:5 2>&1' -n udccd
"
sy=popen 's_client -h rfd -c rfd_atten=0:3 2>&1' -n rfdcn
sy=popen 's_client -h rfd -c rfd_atten=1:3 2>&1' -n rfdcn
sy=popen 's_client -h rfd -c rfd_atten=2:9 2>&1' -n rfdcn
sy=popen 's_client -h rfd -c rfd_atten=3:9 2>&1' -n rfdcn
....


== Appendix B - Example rdbe_atten= output

The following is an example log display output for the `rdbe_atten=`
command (as invoked by the SNAP `auto` procedure) from the KPGO 12m
using the example `ifdbb` procedure in Appendix A.

There are three things to notice here:

. The attenuator settings are all approximately in `10`-`15` dB range.

. The RMSs are all about `20`.

. There is some time variation in the attenuator and RMS values. This
is normal. Large time varying RFI may significantly increase the
variation.

....
19:01:59;auto
19:02:00/rdbe_attenb/,,, 0,13.5,18.9, 1,14.5,19.7
19:02:00/rdbe_attena/,,, 0,12.5,19.8, 1,14.5,19.7
19:02:00/rdbe_attenc/,,, 0,15.5,19.6, 1,13.5,20.6
19:02:00/rdbe_attend/,,, 0,14.0,19.3, 1,13.0,20.6
19:02:01;auto
19:02:01/rdbe_attend/,,, 0,14.0,20.0, 1,13.0,20.2
19:02:01/rdbe_attenb/,,, 0,13.0,20.3, 1,14.5,19.4
19:02:01/rdbe_attena/,,, 0,12.5,20.5, 1,14.0,21.0
19:02:01/rdbe_attenc/,,, 0,15.5,19.9, 1,13.5,20.0
19:02:02;auto
19:02:03/rdbe_attenc/,,, 0,15.5,19.5, 1,13.5,19.4
19:02:03/rdbe_attenb/,,, 0,13.0,20.1, 1,14.0,19.7
19:02:03/rdbe_attena/,,, 0,13.0,19.4, 1,14.5,19.8
19:02:03/rdbe_attend/,,, 0,14.0,19.8, 1,13.0,19.9
19:02:03;auto
19:02:04/rdbe_attenb/,,, 0,12.5,20.8, 1,14.5,19.7
19:02:04/rdbe_attenc/,,, 0,15.0,20.2, 1,13.5,20.6
19:02:04/rdbe_attena/,,, 0,12.5,19.8, 1,14.5,19.4
19:02:04/rdbe_attend/,,, 0,13.5,20.6, 1,13.0,20.4
....
